{"level":"error","message":"Database connection error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:10:5)"}
{"level":"error","message":"Database connection error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:10:5)"}
{"level":"error","message":"Database connection error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:10:5)"}
{"level":"error","message":"Database connection error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:10:5)"}
{"code":"3D000","file":"postinit.c","length":91,"level":"error","line":"1021","message":"Database connection error: database \"ostad\" does not exist","name":"error","routine":"InitPostgres","severity":"FATAL","stack":"error: database \"ostad\" does not exist\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:10:5)"}
{"code":"3D000","file":"postinit.c","length":91,"level":"error","line":"1021","message":"Database connection error: database \"ostad\" does not exist","name":"error","routine":"InitPostgres","severity":"FATAL","stack":"error: database \"ostad\" does not exist\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:10:5)"}
{"level":"error","message":"ENOENT: no such file or directory, open 'C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\uploads\\images\\book_image-1743782700064.png'"}
{"level":"error","message":"Book is not defined"}
{"code":"42601","file":"scan.l","length":100,"level":"error","line":"1245","message":"Database connection error: syntax error at or near \"created_at\"","name":"error","position":"682","routine":"scanner_yyerror","severity":"ERROR","stack":"error: syntax error at or near \"created_at\"\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:16:5)"}
{"level":"error","message":"Expected double-quoted property name in JSON at position 28 (line 4 column 1)"}
{"code":"42601","file":"scan.l","length":101,"level":"error","line":"1245","message":"Database connection error: syntax error at or near \"created_at\"","name":"error","position":"1033","routine":"scanner_yyerror","severity":"ERROR","stack":"error: syntax error at or near \"created_at\"\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:16:5)"}
{"code":"42601","file":"scan.l","length":101,"level":"error","line":"1245","message":"Database connection error: syntax error at or near \"created_at\"","name":"error","position":"1035","routine":"scanner_yyerror","severity":"ERROR","stack":"error: syntax error at or near \"created_at\"\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:16:5)"}
{"code":"42601","file":"scan.l","length":101,"level":"error","line":"1245","message":"Database connection error: syntax error at or near \"created_at\"","name":"error","position":"1039","routine":"scanner_yyerror","severity":"ERROR","stack":"error: syntax error at or near \"created_at\"\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:16:5)"}
{"level":"error","message":"Unexpected field"}
{"level":"error","message":"Expected property name or '}' in JSON at position 1 (line 1 column 2)"}
{"level":"error","message":"Expected property name or '}' in JSON at position 1 (line 1 column 2)"}
{"level":"error","message":"Unexpected field"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database connection error: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)","syscall":"connect"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"323","message":"Database connection error: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:13:5)"}
{"code":"23505","constraint":"pg_class_relname_nsp_index","detail":"Key (relname, relnamespace)=(books_id_seq, 2200) already exists.","file":"nbtinsert.c","length":255,"level":"error","line":"666","message":"Database connection error: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectDB (/app/src/config/db.js:16:5)","table":"pg_class"}
{"code":"ENOTFOUND","errno":-3008,"hostname":"postgres","level":"error","message":"Database connection error: getaddrinfo ENOTFOUND postgres","stack":"Error: getaddrinfo ENOTFOUND postgres\n    at C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async connectDB (C:\\Users\\shahabuddin akhon hr\\Desktop\\Ostad\\backend\\src\\config\\db.js:13:5)","syscall":"getaddrinfo"}
